// <auto-generated />
using System;
using DevHub.Modules.ExecutorRegistry;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DevHub.Modules.ExecutorRegistry.Migrations
{
    [DbContext(typeof(ExecutorRegistryDbContext))]
    [Migration("20260516131409_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("executor_registry")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DevHub.Modules.ExecutorRegistry.Entities.CheckpointContract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AllowedOutcomesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("allowed_outcomes_json");

                    b.Property<string>("CheckpointKey")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("checkpoint_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<Guid>("ExecutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("executor_id");

                    b.Property<string>("RequiredRoleKey")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("required_role_key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_checkpoint_contracts");

                    b.HasIndex("ExecutorId", "CheckpointKey")
                        .IsUnique()
                        .HasDatabaseName("ix_checkpoint_contracts_executor_id_checkpoint_key");

                    b.ToTable("checkpoint_contracts", "executor_registry");
                });

            modelBuilder.Entity("DevHub.Modules.ExecutorRegistry.Entities.ExecutorBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("ExecutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("executor_id");

                    b.Property<string>("ProjectType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("project_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_bindings");

                    b.HasIndex("ExecutorId")
                        .HasDatabaseName("ix_bindings_executor_id");

                    b.HasIndex("ProjectType")
                        .IsUnique()
                        .HasDatabaseName("ix_bindings_project_type")
                        .HasFilter("\"deleted_at\" IS NULL");

                    b.ToTable("bindings", "executor_registry");
                });

            modelBuilder.Entity("DevHub.Modules.ExecutorRegistry.Entities.ExecutorRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("base_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CredentialsRef")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("credentials_ref");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_executors");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_executors_key")
                        .HasFilter("\"deleted_at\" IS NULL");

                    b.ToTable("executors", "executor_registry");
                });

            modelBuilder.Entity("DevHub.Modules.ExecutorRegistry.Entities.CheckpointContract", b =>
                {
                    b.HasOne("DevHub.Modules.ExecutorRegistry.Entities.ExecutorRegistration", null)
                        .WithMany("CheckpointContracts")
                        .HasForeignKey("ExecutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_checkpoint_contracts_executors_executor_id");
                });

            modelBuilder.Entity("DevHub.Modules.ExecutorRegistry.Entities.ExecutorRegistration", b =>
                {
                    b.Navigation("CheckpointContracts");
                });
#pragma warning restore 612, 618
        }
    }
}
