// <auto-generated />
using System;
using DevHub.Modules.WorkItems;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DevHub.Modules.WorkItems.Migrations
{
    [DbContext(typeof(WorkItemsDbContext))]
    [Migration("20260516160231_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("work_items")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DevHub.Modules.WorkItems.Entities.CheckpointSignal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CheckpointKey")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("checkpoint_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExecutorResponseAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executor_response_at");

                    b.Property<int?>("ExecutorResponseStatus")
                        .HasColumnType("integer")
                        .HasColumnName("executor_response_status");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("outcome");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset>("SignaledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signaled_at");

                    b.Property<Guid>("SignaledByMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("signaled_by_member_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_item_id");

                    b.HasKey("Id")
                        .HasName("pk_checkpoint_signals");

                    b.HasIndex("WorkItemId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_checkpoint_signals_work_item_id_idempotency_key")
                        .HasFilter("\"idempotency_key\" IS NOT NULL");

                    b.HasIndex("WorkItemId", "SignaledAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_checkpoint_signals_work_item_id_signaled_at");

                    b.ToTable("checkpoint_signals", "work_items");
                });

            modelBuilder.Entity("DevHub.Modules.WorkItems.Entities.WorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_member_id");

                    b.Property<string>("CurrentCheckpointKey")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("current_checkpoint_key");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("current_status");

                    b.Property<string>("ExecutorCorrelationMarker")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("executor_correlation_marker");

                    b.Property<Guid>("ExecutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("executor_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_work_items");

                    b.HasIndex("ExecutorId", "ExecutorCorrelationMarker")
                        .IsUnique()
                        .HasDatabaseName("ix_work_items_executor_id_executor_correlation_marker");

                    b.HasIndex("ProjectId", "CurrentStatus")
                        .HasDatabaseName("ix_work_items_project_id_current_status");

                    b.ToTable("work_items", "work_items");
                });
#pragma warning restore 612, 618
        }
    }
}
